// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2017-06-25 01:25:37.872454531 +0800 CST

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
  "swagger" : "2.0",
  "info" : {
    "description" : "API BAFCommon",
    "version" : "1.0.0",
    "title" : "BAFCommon",
    "contact" : {
      "email" : "itdaa@bussan.co.id"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host" : "apibafcommonuat.bafsp.bussan.co.id",
  "basePath" : "/api/v1/apibafcommon",
  "tags" : [ {
    "name" : "Tracking Order",
    "description" : "Operations available for Application Module"
  } ],

  "paths" : {
    "/common/datadetailorder/list" : {
      "post" : {
        "tags" : [ "Data Detail Order" ],
        "summary" : "Data Detail Order",
        "description" : "Data Detail Order",
        "operationId" : "Data Detail Order",
    "consumes" : [ "application/json" ],
    "produces" : [ "application/json" ],
    "parameters" : [ 
      {
        "description": "Data Detail Order",
        "name": "Ordertrxhid",
        "in": "body",
        "required": false,
        "schema": {
          "$ref" : "#/definitions/DataDetailOrder"
        }
      }
      ],
      "responses" : {
         "200" : {
          "description" : "Data Found"
          },
          "404" : {
          "description" : "Data Not Found"
          }
        }
      }
    },

    "/common/datadetailorderresubmit/list" : {
      "post" : {
        "tags" : [ "Data Detail Order Resubmit" ],
        "summary" : "Data Detail Order Resubmit",
        "description" : "Data Detail Order Resubmit",
        "operationId" : "Data Detail Order Resubmit",
    "consumes" : [ "application/json" ],
    "produces" : [ "application/json" ],
    "parameters" : [ 
      {
        "description": "Data Detail Order Resubmit",
        "name": "ordertrxhid",
        "in": "body",
        "required": false,
        "schema": {
          "$ref" : "#/definitions/DataDetailOrdeResubmitr"
        }
      }
      ],
      "responses" : {
         "200" : {
          "description" : "Data Found"
          },
          "404" : {
          "description" : "Data Not Found"
          }
        }
      }
    },

    "/common/dataquickorder/list" : {
      "post" : {
        "tags" : [ "Data Quick Order" ],
        "summary" : "Data Quick Order",
        "description" : "Data Quick Order",
        "operationId" : "Data Quick Order",
    "consumes" : [ "application/json" ],
    "produces" : [ "application/json" ],
    "parameters" : [ 
      {
        "description": "Data Quick Order",
        "name": "Ordertrxhid",
        "in": "body",
        "required": false,
        "schema": {
          "$ref" : "#/definitions/DataQuickOrder"
        }
      }
      ],
      "responses" : {
         "200" : {
          "description" : "Data Found"
          },
          "404" : {
          "description" : "Data Not Found"
          }
        }
      }
    },

    "/common/dataquickorderresubmit/list" : {
      "post" : {
        "tags" : [ "Data Quick Order Resubmit" ],
        "summary" : "Data Quick Order Resubmit",
        "description" : "Data Quick Order Resubmit",
        "operationId" : "Data Quick Order Resubmit",
    "consumes" : [ "application/json" ],
    "produces" : [ "application/json" ],
    "parameters" : [ 
      {
        "description": "Data DetaiQuickl Order Resubmit",
        "name": "Ordertrxhid",
        "in": "body",
        "required": false,
        "schema": {
          "$ref" : "#/definitions/DataQuickOrdeResubmitr"
        }
      }
      ],
      "responses" : {
         "200" : {
          "description" : "Data Found"
          },
          "404" : {
          "description" : "Data Not Found"
          }
        }
      }
    },

    "/common/listorder/list" : {
      "post" : {
        "tags" : [ "List Order" ],
        "summary" : "List Order",
        "description" : "List Order",
        "operationId" : "List Order",
    "consumes" : [ "application/json" ],
    "produces" : [ "application/json" ],
    "parameters" : [ 
      {
        "description": "List Order",
        "name": "Usrprocess,Isapproved,Lobcode,Dtmcrt,Dtmcrtto",
        "in": "body",
        "required": false,
        "schema": {
          "$ref" : "#/definitions/ListOrder"
        }
      }
      ],
      "responses" : {
         "200" : {
          "description" : "Data Found"
          },
          "404" : {
          "description" : "Data Not Found"
          }
        }
      }
    },

    "/common/accesscontent/list" : {
      "post" : {
        "tags" : [ "Access Content" ],
        "summary" : "Access Content",
        "description" : "Access Content",
        "operationId" : "Access Content",
    "consumes" : [ "application/json" ],
    "produces" : [ "application/json" ],
    "parameters" : [ 
      {
        "description": "Access Content",
        "name": "Userid & Contentcode",
        "in": "body",
        "required": false,
        "schema": {
          "$ref" : "#/definitions/AccessContent"
        }
      }
      ],
      "responses" : {
         "200" : {
          "description" : "Data Found"
          },
          "404" : {
          "description" : "Data Not Found"
          }
        }
      }
    },

    "/common/generalsetting/list" : {
      "post" : {
        "tags" : [ "General Setting" ],
        "summary" : "General Setting",
        "description" : "General Setting",
        "operationId" : "General Setting",
    "consumes" : [ "application/json" ],
    "produces" : [ "application/json" ],
    "parameters" : [ 
      {
        "description": "General Setting",
        "name": "Generalsettingcode",
        "in": "body",
        "required": false,
        "schema": {
          "$ref" : "#/definitions/Generalsettingcode"
        }
      }
      ],
      "responses" : {
         "200" : {
          "description" : "Data Found"
          },
          "404" : {
          "description" : "Data Not Found"
          }
        }
      }
    },

    "/common/hierarki/list" : {
      "post" : {
        "tags" : [ "Hierarki" ],
        "summary" : " Hierarki",
        "description" : "Hierarki",
        "operationId" : "Hierarki",
    "consumes" : [ "application/json" ],
    "produces" : [ "application/json" ],
    "parameters" : [ 
      {
        "description": "Hierarki",
        "name": "Userid & Contentcode",
        "in": "body",
        "required": false,
        "schema": {
          "$ref" : "#/definitions/Hierarki"
        }
      }
      ],
      "responses" : {
         "200" : {
          "description" : "Data Found"
          },
          "404" : {
          "description" : "Data Not Found"
          }
        }
      }
    },
  
    "/common/trackingorder/list" : {
      "post" : {
        "tags" : [ "Tracking Order" ],
        "summary" : "Get All Tracking Order",
        "description" : "Get List Tracking Order",
        "operationId" : "Get All Tracking Order",
    "consumes" : [ "application/json" ],
    "produces" : [ "application/json" ],
    "parameters" : [ 
      {
        "description": "Get List Tracking Order",
        "name": "Ordertrxhid",
        "in": "body",
        "required": false,
        "schema": {
          "$ref" : "#/definitions/ListTrackingOrder"
        }
      }
      ],
      "responses" : {
         "200" : {
          "description" : "Data Found"
          },
          "404" : {
          "description" : "Data Not Found"
          }
        }
      }
    }  


  }
    
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
